name: test
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: hello
      run: echo "hello"
