name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted
    name: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hello
      run: echo "hello"
