name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
runs-on: [self-hosted, Linux]
jobs:
  test:
    name: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hello
      run: echo "hello"
